//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 01:00:20 AM EET 
//


package ua.nure.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.nure.entity
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostUpdateZakazResponse }
     *
     */
    public PostUpdateZakazResponse createPostUpdateZakazResponse() {
        return new PostUpdateZakazResponse();
    }

    /**
     * Create an instance of {@link GetZakazResponse }
     *
     */
    public GetZakazResponse createGetZakazResponse() {
        return new GetZakazResponse();
    }

    /**
     * Create an instance of {@link Zakaz }
     *
     */
    public Zakaz createZakaz() {
        return new Zakaz();
    }

    /**
     * Create an instance of {@link GetZakazRequest }
     *
     */
    public GetZakazRequest createGetZakazRequest() {
        return new GetZakazRequest();
    }

    /**
     * Create an instance of {@link User }
     *
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link PostDeleteZakazRequest }
     *
     */
    public PostDeleteZakazRequest createPostDeleteZakazRequest() {
        return new PostDeleteZakazRequest();
    }

    /**
     * Create an instance of {@link PostCreateZakazResponse }
     *
     */
    public PostCreateZakazResponse createPostCreateZakazResponse() {
        return new PostCreateZakazResponse();
    }

    /**
     * Create an instance of {@link PostDeleteZakazResponse }
     *
     */
    public PostDeleteZakazResponse createPostDeleteZakazResponse() {
        return new PostDeleteZakazResponse();
    }

    /**
     * Create an instance of {@link PostUpdateZakazRequest }
     *
     */
    public PostUpdateZakazRequest createPostUpdateZakazRequest() {
        return new PostUpdateZakazRequest();
    }

    /**
     * Create an instance of {@link GetReadSnapshotResponse }
     *
     */
    public GetReadSnapshotResponse createGetReadSnapshotResponse() {
        return new GetReadSnapshotResponse();
    }

    /**
     * Create an instance of {@link ZakazView }
     *
     */
    public ZakazView createZakazView() {
        return new ZakazView();
    }

    /**
     * Create an instance of {@link PostAssignZakazRequest }
     *
     */
    public PostAssignZakazRequest createPostAssignZakazRequest() {
        return new PostAssignZakazRequest();
    }

    /**
     * Create an instance of {@link PostAssignZakazResponse }
     *
     */
    public PostAssignZakazResponse createPostAssignZakazResponse() {
        return new PostAssignZakazResponse();
    }

    /**
     * Create an instance of {@link PostCreateZakazRequest }
     *
     */
    public PostCreateZakazRequest createPostCreateZakazRequest() {
        return new PostCreateZakazRequest();
    }

    /**
     * Create an instance of {@link GetReadSnapshotRequest }
     *
     */
    public GetReadSnapshotRequest createGetReadSnapshotRequest() {
        return new GetReadSnapshotRequest();
    }

    /**
     * Create an instance of {@link Auto }
     *
     */
    public Auto createAuto() {
        return new Auto();
    }

}
