//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 01:00:20 AM EET 
//


package ua.nure.entity;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.sql.Timestamp;
import java.util.Date;
import java.util.GregorianCalendar;


/**
 * <p>Java class for zakaz complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zakaz">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="create_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="assign_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="auto_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="order_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zakaz", propOrder = {
    "id",
    "address1",
    "address2",
    "category",
    "createDateTime",
    "assignDateTime",
    "autoId",
    "orderStatus",
    "userId"
})
public class Zakaz {

    protected int id;
    @XmlElement(required = true)
    protected String address1;
    @XmlElement(required = true)
    protected String address2;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(name = "create_date_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDateTime;
    @XmlElement(name = "assign_date_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar assignDateTime;
    @XmlElement(name = "auto_id")
    protected int autoId;
    @XmlElement(name = "order_status", required = true)
    protected String orderStatus;
    @XmlElement(name = "user_id")
    protected int userId;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDateTime(XMLGregorianCalendar value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the assignDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAssignDateTime() {
        return assignDateTime;
    }

    /**
     * Sets the value of the assignDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAssignDateTime(XMLGregorianCalendar value) {
        this.assignDateTime = value;
    }

    /**
     * Gets the value of the autoId property.
     * 
     */
    public int getAutoId() {
        return autoId;
    }

    /**
     * Sets the value of the autoId property.
     * 
     */
    public void setAutoId(int value) {
        this.autoId = value;
    }

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderStatus(String value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    public static ua.nure.sql.Zakaz toSqlType(Zakaz zakaz){
        ua.nure.sql.Zakaz sqlZakaz = new ua.nure.sql.Zakaz();
        sqlZakaz.setId(zakaz.getId());
        sqlZakaz.setAutoId(zakaz.getAutoId());
        sqlZakaz.setAddress1(zakaz.getAddress1());
        sqlZakaz.setAddress2(zakaz.getAddress2());
        if(zakaz.getCreateDateTime()!=null){
            Timestamp create = new Timestamp(zakaz.getCreateDateTime().toGregorianCalendar().getTimeInMillis());
            sqlZakaz.setCreateDateTime(create);
        }
        if (zakaz.getAssignDateTime()!=null){
            Timestamp assign = new Timestamp(zakaz.getAssignDateTime().toGregorianCalendar().getTimeInMillis());
            sqlZakaz.setAssignDateTime(assign);
        }
        sqlZakaz.setUserId(zakaz.getUserId());
        sqlZakaz.setCategory(zakaz.getCategory());
        sqlZakaz.setOrderStatus(zakaz.getOrderStatus());
        return sqlZakaz;
    }
    public static Zakaz toXmlType(ua.nure.sql.Zakaz zakaz) throws DatatypeConfigurationException {
        Zakaz xmlZakaz = new Zakaz();
        if(zakaz.getCreateDateTime()!=null){
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTimeInMillis(zakaz.getCreateDateTime().getTime());
            xmlZakaz.setCreateDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar(gc));
        }
        if(zakaz.getAssignDateTime()!=null){
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTimeInMillis(zakaz.getAssignDateTime().getTime());
            xmlZakaz.setAssignDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar(gc));
        }
        xmlZakaz.setId(zakaz.getId());
        xmlZakaz.setAutoId(zakaz.getAutoId());
        xmlZakaz.setAddress1(zakaz.getAddress1());
        xmlZakaz.setAddress2(zakaz.getAddress2());
        xmlZakaz.setUserId(zakaz.getUserId());
        xmlZakaz.setCategory(zakaz.getCategory());
        xmlZakaz.setOrderStatus(zakaz.getOrderStatus());
        return xmlZakaz;
    }
}
