//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.16 at 01:00:20 AM EET 
//


package ua.nure.entity;

import com.sun.xml.internal.ws.developer.UsesJAXBContext;
import org.hibernate.annotations.Immutable;
import ua.nure.sql.Zakaz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.sql.Timestamp;
import java.util.Date;
import java.util.GregorianCalendar;


/**
 * <p>Java class for zakaz_view complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zakaz_view">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zakaz_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="user_fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="create_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assign_date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="auto_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="order_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sign_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driver_fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auto_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zakaz_view", propOrder = {
    "zakazId",
    "userId",
    "userFullname",
    "telephone",
    "createDateTime",
    "address1",
    "address2",
    "category",
    "assignDateTime",
    "autoId",
    "orderStatus",
    "signNumber",
    "driverFullname",
    "autoName"
})
public class ZakazView {

    @XmlElement(name = "zakaz_id")
    protected int zakazId;
    @XmlElement(name = "user_id")
    protected int userId;
    @XmlElement(name = "user_fullname", required = true)
    protected String userFullname;
    @XmlElement(required = true)
    protected String telephone;
    @XmlElement(name = "create_date_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDateTime;
    @XmlElement(name = "Address1", required = true)
    protected String address1;
    @XmlElement(name = "Address2", required = true)
    protected String address2;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(name = "assign_date_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar assignDateTime;
    @XmlElement(name = "auto_id")
    protected int autoId;
    @XmlElement(name = "order_status", required = true)
    protected String orderStatus;
    @XmlElement(name = "sign_number", required = true)
    protected String signNumber;
    @XmlElement(name = "driver_fullname", required = true)
    protected String driverFullname;
    @XmlElement(name = "auto_name", required = true)
    protected String autoName;

    /**
     * Gets the value of the zakazId property.
     * 
     */
    public int getZakazId() {
        return zakazId;
    }

    /**
     * Sets the value of the zakazId property.
     * 
     */
    public void setZakazId(int value) {
        this.zakazId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userFullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFullname() {
        return userFullname;
    }

    /**
     * Sets the value of the userFullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFullname(String value) {
        this.userFullname = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephone(String value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDateTime(XMLGregorianCalendar value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the assignDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAssignDateTime() {
        return assignDateTime;
    }

    /**
     * Sets the value of the assignDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAssignDateTime(XMLGregorianCalendar value) {
        this.assignDateTime = value;
    }

    /**
     * Gets the value of the autoId property.
     * 
     */
    public int getAutoId() {
        return autoId;
    }

    /**
     * Sets the value of the autoId property.
     * 
     */
    public void setAutoId(int value) {
        this.autoId = value;
    }

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderStatus(String value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the signNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignNumber() {
        return signNumber;
    }

    /**
     * Sets the value of the signNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignNumber(String value) {
        this.signNumber = value;
    }

    /**
     * Gets the value of the driverFullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverFullname() {
        return driverFullname;
    }

    /**
     * Sets the value of the driverFullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverFullname(String value) {
        this.driverFullname = value;
    }

    /**
     * Gets the value of the autoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoName() {
        return autoName;
    }

    /**
     * Sets the value of the autoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoName(String value) {
        this.autoName = value;
    }

    public static ZakazView toXmlType(ua.nure.sql.ZakazView zakazView) throws DatatypeConfigurationException {
        ZakazView xmlZakazView = new ZakazView();

        if(zakazView.getCreateDateTime()!=null){
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTimeInMillis(zakazView.getAssignDateTime().getTime());
            xmlZakazView.setCreateDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar(gc));
        }
        if(zakazView.getAssignDateTime()!=null){
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTimeInMillis(zakazView.getAssignDateTime().getTime());
            xmlZakazView.setAssignDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar(gc));
        }
        xmlZakazView.setZakazId(zakazView.getZakazId());
        xmlZakazView.setUserId(zakazView.getUserId());
        xmlZakazView.setUserFullname(zakazView.getUserFullname());
        xmlZakazView.setTelephone(zakazView.getTelephone());
        xmlZakazView.setAddress1(zakazView.getAddress1());
        xmlZakazView.setAddress2(zakazView.getAddress2());
        xmlZakazView.setCategory(zakazView.getCategory());
        xmlZakazView.setAutoId(zakazView.getAutoId());
        xmlZakazView.setOrderStatus(zakazView.getOrderStatus());
        if(zakazView.getSignNumber()!=null){
            xmlZakazView.setSignNumber(zakazView.getSignNumber());
        }
        if (zakazView.getDriverFullname()!=null){
            xmlZakazView.setDriverFullname(zakazView.getDriverFullname());
        }
        if (zakazView.getAutoName()!=null){
            xmlZakazView.setAutoName(zakazView.getAutoName());
        }
        return xmlZakazView;
    }

    public static ua.nure.sql.ZakazView toSqlType(ZakazView zakazView){
        ua.nure.sql.ZakazView sqlZakazView = new ua.nure.sql.ZakazView();
        if(zakazView.getCreateDateTime()!=null){
            Timestamp create = new Timestamp(zakazView.getCreateDateTime().toGregorianCalendar().getTimeInMillis());
            sqlZakazView.setCreateDateTime(create);
        }
        if (zakazView.getAssignDateTime()!=null){
            Timestamp assign = new Timestamp(zakazView.getAssignDateTime().toGregorianCalendar().getTimeInMillis());
            sqlZakazView.setAssignDateTime(assign);
        }
        sqlZakazView.setUserId(zakazView.getUserId());
        sqlZakazView.setUserFullname(zakazView.getUserFullname());
        sqlZakazView.setTelephone(zakazView.getTelephone());
        sqlZakazView.setAddress1(zakazView.getAddress1());
        sqlZakazView.setAddress2(zakazView.getAddress2());
        sqlZakazView.setCategory(zakazView.getCategory());
        sqlZakazView.setAutoId(zakazView.getAutoId());
        sqlZakazView.setOrderStatus(zakazView.getOrderStatus());
        if(zakazView.getSignNumber()!=null){
            sqlZakazView.setSignNumber(zakazView.getSignNumber());
        }
        if (zakazView.getDriverFullname()!=null){
            sqlZakazView.setDriverFullname(zakazView.getDriverFullname());
        }
        if (sqlZakazView.getAutoName()!=null){
            sqlZakazView.setAutoName(zakazView.getAutoName());
        }
        return sqlZakazView;
    }

}
