//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 03:28:37 PM EET 
//


package ua.nure.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.nure.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFilterAutoRequest }
     * 
     */
    public GetFilterAutoRequest createGetFilterAutoRequest() {
        return new GetFilterAutoRequest();
    }

    /**
     * Create an instance of {@link PostAddAutoRequest }
     * 
     */
    public PostAddAutoRequest createPostAddAutoRequest() {
        return new PostAddAutoRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Auto }
     * 
     */
    public Auto createAuto() {
        return new Auto();
    }

    /**
     * Create an instance of {@link PostUpdateAutoRequest }
     * 
     */
    public PostUpdateAutoRequest createPostUpdateAutoRequest() {
        return new PostUpdateAutoRequest();
    }

    /**
     * Create an instance of {@link GetFilterAutoResponse }
     * 
     */
    public GetFilterAutoResponse createGetFilterAutoResponse() {
        return new GetFilterAutoResponse();
    }

    /**
     * Create an instance of {@link PostUpdateAutoResponse }
     * 
     */
    public PostUpdateAutoResponse createPostUpdateAutoResponse() {
        return new PostUpdateAutoResponse();
    }

    /**
     * Create an instance of {@link GetAllAutoResponse }
     * 
     */
    public GetAllAutoResponse createGetAllAutoResponse() {
        return new GetAllAutoResponse();
    }

    /**
     * Create an instance of {@link PostDeleteAutoRequest }
     * 
     */
    public PostDeleteAutoRequest createPostDeleteAutoRequest() {
        return new PostDeleteAutoRequest();
    }

    /**
     * Create an instance of {@link PostDeleteAutoResponse }
     * 
     */
    public PostDeleteAutoResponse createPostDeleteAutoResponse() {
        return new PostDeleteAutoResponse();
    }

    /**
     * Create an instance of {@link GetAllAutoRequest }
     * 
     */
    public GetAllAutoRequest createGetAllAutoRequest() {
        return new GetAllAutoRequest();
    }

    /**
     * Create an instance of {@link PostAddAutoResponse }
     * 
     */
    public PostAddAutoResponse createPostAddAutoResponse() {
        return new PostAddAutoResponse();
    }

}
