//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 12:44:12 PM EET 
//


package ua.nure.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.nure.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link PostUpdateUserRequest }
     * 
     */
    public PostUpdateUserRequest createPostUpdateUserRequest() {
        return new PostUpdateUserRequest();
    }

    /**
     * Create an instance of {@link PostUserRequest }
     * 
     */
    public PostUserRequest createPostUserRequest() {
        return new PostUserRequest();
    }

    /**
     * Create an instance of {@link PostUserResponse }
     * 
     */
    public PostUserResponse createPostUserResponse() {
        return new PostUserResponse();
    }

    /**
     * Create an instance of {@link PostUpdateUserResponse }
     * 
     */
    public PostUpdateUserResponse createPostUpdateUserResponse() {
        return new PostUpdateUserResponse();
    }

}
